services:
  db:
    image: postgres
    restart: always
    #include the file with the environment variables 
    env_file: ./config/.env
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    #include the file with the environment variables 
    env_file: ./config/.env
    ports:
      - "5050:80"
    networks:
      - app_net
    depends_on:
      - db

networks:
  app_net:
    driver: bridge

volumes:
  pgdata:
